version: "3.9"

services:
  proxy:
    image: nginx
    networks:
      - frontend
    depends_on:
      - app
      - web
    ports: 
      - "80:80"
    volumes: 
      - ./nginx.conf:/etc/nginx/nginx.conf

  db:
    image: mysql
    networks:
      - backend
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=userdb
      - MYSQL_USER=user
      - MYSQL_PASSWORD=password

  app:
    image: zz061945/awstraining_1_app
    networks:
      - frontend
      - backend
    depends_on:
      - db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://db:3306/userdb
      - SPRING_DATASOURCE_USERNAME=user
      - SPRING_DATASOURCE_PASSWORD=password

  web:
    image: zz061945/awstraining_1_web
    networks:
      - frontend
    depends_on:
      - app
    environment: 
      - REACT_APP_API_HOST="http://app:8080"

networks:
 frontend:
   driver: bridge
 backend:
   driver: bridge
