AWSTemplateFormatVersion: '2010-09-09'
Description: Lambda function from cloud formation from zhen's aws training
Resources:
  lambda:
    Type: AWS::Lambda::Function
    Properties:
      Runtime: nodejs12.x
      Role: arn:aws:iam::160071257600:role/aws-training-zhen-lambda-cloudformation
      Handler: index.handler
      Code:
        ZipFile: |
            exports.handler = async (event, context) => {
                //console.log('Received event:', JSON.stringify(event, null, 2));
                console.log('value1 =', event.key1);
                console.log('value2 =', event.key2);
                console.log('value3 =', event.key3);
                console.log('Lambda created by cloudFormation by Zhen');
                return context.logStreamName;  // Echo back the first key value
            };
      Description: Invoke a function during stack creation.
      TracingConfig:
        Mode: Active
  LambdaInvocationAlarm:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmDescription: Lambda invocations
      AlarmName: LambdaInvocationsAlarm

